FROM fluentd
USER root
#RUN ["gem", "install", "elasticsearch", "-v", "8.1.2"]
#RUN ["gem", "install", "fluent-plugin-elasticsearch", "--no-document", "--version", "5.2.2"]
RUN ["gem", "install", "fluent-plugin-opensearch", "--no-document"]
USER fluent
