version: '3.8'
services:
  librespeed:
    build:
      context: .
      dockerfile: Dockerfile
    image: unittest
    expose:
      - 80
    restart: unless-stopped
    volumes:
      - ./database/:/database/
    environment:
      MODE: frontend
      TITLE: "LibreSpeed"
      TELEMETRY: "true"
      ENABLE_ID_OBFUSCATION: "true"
      PASSWORD: "1234"
    networks:
      - mynet 
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 
          127.0.0.1:24224
        tag: speedtest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.librespeed.entrypoints=http"
      - "traefik.http.routers.librespeed.rule=PathPrefix(`/`)"
      - "traefik.http.services.librespeed.loadbalancer.server.port=80"
      - "traefik.http.routers.librespeed.middlewares=add-client-ip,testheader"  
      - "traefik.http.middlewares.add-client-ip.headers.customrequestheaders.X-Client-IP=X-Forwarded-For"
      - "traefik.http.middlewares.testheader.headers.accesscontrolallowmethods=GET,OPTIONS,PUT"
      - "traefik.http.middlewares.testheader.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.testheader.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.testheader.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.testheader.headers.addvaryheader=true"
  reverse-proxy:
    image: traefik:v2.11
    command: --api.insecure=true --providers.docker --entrypoints.http.address=:80 --entrypoints.kibana.address=:5601 --accesslog
    ports:
      - "80:80"
      - "8080:8080"
      - "5601:5601"
    networks:
      - mynet
    depends_on:
      - librespeed 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 
          127.0.0.1:24224
        tag: traefik

networks:
  mynet:
    name: mynet
    external: true
