version: '3.8'

services:
  librespeed:
    build:
      context: .
      dockerfile: Dockerfile
    image: unittest
    #container_name: librespeed
#    ports:
#      - "80:80"
#    volumes:
      #- result:/var/www/html/result
      #- .:/speedtest
      #- ./unit-config.json:/docker-entrypoint.d/unit-config.json
      #- ./docker/entrypoint.sh:/docker-entrypoint.d/entrypoint.sh     
      #- ./docker/servers.json:/servers.json
      #- ./database/db.sql:/database/db.sql 
    expose:
      - 80
    restart: unless-stopped
    environment:
      MODE: frontend
      TITLE: "LibreSpeed"
      TELEMETRY: "true"
      ENABLE_ID_OBFUSCATION: "true"
      #REDACT_IP_ADDRESSES: "false"
      PASSWORD: "1234"
      #EMAIL:
      #DISABLE_IPINFO: "false"
      #IPINFO_APIKEY: "your api key"
      #DISTANCE: "km"
      #WEBPORT: 8080
    networks:
      - mynet 
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 
          127.0.0.1:24224
        tag: speedtest

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.librespeed.entrypoints=http"
      - "traefik.http.routers.librespeed.rule=PathPrefix(`/`)"
      - "traefik.http.routers.librespeed.service=speedtest"      
      - "traefik.http.services.speedtest.loadbalancer.server.port=80"



  reverse-proxy:
    image: traefik:v2.11
    command: --api.insecure=true --providers.docker --entrypoints.http.address=:80 --entrypoints.websecure.address=:443 --entrypoints.kibana.address=:5601 --accesslog --accesslog.filepath=/var/log/traefik/access.log
    ports:
      - "80:80"
      - "8080:8080"
      - "5601:5601"
    networks:
      - mynet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 
          127.0.0.1:24224
        tag: traefik

networks:
  mynet:
    name: mynet
    external: true
